data:
  train:
    src_file: ./data/processed/augmented/contractions/en_train_contractions_full.txt
    tgt_file: ./data/processed/augmented/contractions/vi_train_contractions_full.txt
  dev: 
    src_file: ./data/processed/dev/tst2012.en
    tgt_file: ./data/processed/dev/tst2012.vi

utils:
  vocab:
    en: ./utils/vocab/contractions/en.json
    vi: ./utils/vocab/contractions/vi.json
    
  training_runs:
    train_loss: ./utils/runs/contractions/train_loss
    dev_loss: ./utils/runs/contractions/dev_loss
    learning_rate: ./utils/runs/contractions/learning_rate
train:
  num_epochs: 20
  learning_rate: 0.001
  batch_size: 64
model:
  max_sent_len: 120
  embedding_size: 512
  num_heads: 8
  num_encoder_layers: 3
  num_decoder_layers: 3
  dropout: 0.1
  forward_expansion: 4
  checkpoint_path: ./model/contractions_model.pth.tar
